### ISSUE TITLE
`KeyError: 'password'` after relating to application

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/mongodb-operator#138]
# To Reproduce
```sh
juju add-model tutorial
juju deploy mongodb --channel dpe/edge
git clone https://github.com/MiaAltieri/application-charm.git
cd application-charm/
charmcraft pack
juju deploy ./*charm
juju relate mongodb application
```
# Environment
<details>
<summary>cloud-init</summary>

```yaml
#cloud-config
package_upgrade: true
packages:
  - gnome-keyring
  - retry
  - tox
snap:
  commands:
    - snap refresh
    - snap install juju --classic --channel=2.9/stable
    - snap install charmcraft --classic
    - snap install lxd
    - snap install microk8s --classic
    - snap alias microk8s.kubectl kubectl
    - snap install jhack
    - snap connect jhack:dot-local-share-juju snapd
runcmd:
  - adduser ubuntu lxd
  - newgrp lxd
  - lxd init --auto
  - lxc network set lxdbr0 ipv6.address none
  # https://linuxcontainers.org/lxd/docs/master/howto/network_bridge_firewalld/#ufw-add-rules-for-the-bridge
  - ufw allow in on lxdbr0
  - ufw route allow in on lxdbr0
  - ufw route allow out on lxdbr0
  - adduser ubuntu microk8s
  - newgrp microk8s
  - microk8s status --wait-ready
  - retry --times 3 --delay 5 microk8s enable dns
  - microk8s status --wait-ready
  - kubectl rollout status --namespace kube-system --watch --timeout=5m deployments/coredns
  - microk8s enable hostpath-storage
  - kubectl rollout status --namespace kube-system --watch --timeout=5m deployments/hostpath-provisioner
  - runuser ubuntu --login --command "juju bootstrap microk8s micro --agent-version=2.9.29"
  - runuser ubuntu --login --command "juju bootstrap localhost lxd --agent-version=2.9.29"
  - runuser ubuntu --login --command "juju model-defaults logging-config='<root>=INFO; unit=DEBUG'"
  - runuser ubuntu --login --command "microk8s config > ~/.kube/config"
  - runuser ubuntu --login --command "ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''"
  - runuser ubuntu --login --command "cat ~/.ssh/id_ed25519.pub"

```
</details>

Google Cloud compute engine VM on Ubuntu 22.04
<details>
<summary>full details</summary>

```json
{
  "creationTimestamp": "2022-12-12T04:31:18.400-08:00",
  "description": "",
  "id": "7265271972764492281",
  "kind": "compute#instanceTemplate",
  "name": "dev-env",
  "properties": {
    "confidentialInstanceConfig": {
      "enableConfidentialCompute": false
    },
    "description": "",
    "scheduling": {
      "onHostMaintenance": "MIGRATE",
      "provisioningModel": "STANDARD",
      "automaticRestart": true,
      "preemptible": false
    },
    "tags": {},
    "disks": [
      {
        "type": "PERSISTENT",
        "deviceName": "instance-template-1",
        "autoDelete": true,
        "index": 0,
        "boot": true,
        "kind": "compute#attachedDisk",
        "mode": "READ_WRITE",
        "initializeParams": {
          "sourceImage": "projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20221123",
          "diskType": "pd-ssd",
          "diskSizeGb": "50"
        }
      }
    ],
    "networkInterfaces": [
      {
        "stackType": "IPV4_ONLY",
        "name": "nic0",
        "network": "projects/dev-env-369519/global/networks/default",
        "accessConfigs": [
          {
            "name": "External NAT",
            "type": "ONE_TO_ONE_NAT",
            "kind": "compute#accessConfig",
            "networkTier": "PREMIUM"
          }
        ],
        "kind": "compute#networkInterface"
      }
    ],
    "reservationAffinity": {
      "consumeReservationType": "ANY_RESERVATION"
    },
    "canIpForward": false,
    "keyRevocationActionType": "NONE",
    "machineType": "n2-standard-4",
    "metadata": {
      "fingerprint": "8IKJq01FHkM=",
      "kind": "compute#metadata",
      "items": [
        {
          "value": "#cloud-config\npackage_upgrade: true\npackages:\n  - gnome-keyring\n  - retry\n  - tox\nsnap:\n  commands:\n    - snap refresh\n    - snap install juju --classic --channel=2.9/stable\n    - snap install charmcraft --classic\n    - snap install lxd\n    - snap install microk8s --classic\n    - snap alias microk8s.kubectl kubectl\n    - snap install jhack\n    - snap connect jhack:dot-local-share-juju snapd\nruncmd:\n  - adduser ubuntu lxd\n  - newgrp lxd\n  - lxd init --auto\n  - lxc network set lxdbr0 ipv6.address none\n  # https://linuxcontainers.org/lxd/docs/master/howto/network_bridge_firewalld/#ufw-add-rules-for-the-bridge\n  - ufw allow in on lxdbr0\n  - ufw route allow in on lxdbr0\n  - ufw route allow out on lxdbr0\n  - adduser ubuntu microk8s\n  - newgrp microk8s\n  - microk8s status --wait-ready\n  - retry --times 3 --delay 5 microk8s enable dns\n  - microk8s status --wait-ready\n  - kubectl rollout status --namespace kube-system --watch --timeout=5m deployments/coredns\n  - microk8s enable hostpath-storage\n  - kubectl rollout status --namespace kube-system --watch --timeout=5m deployments/hostpath-provisioner\n  - runuser ubuntu --login --command \"juju bootstrap microk8s micro --agent-version=2.9.29\"\n  - runuser ubuntu --login --command \"juju bootstrap localhost lxd --agent-version=2.9.29\"\n  - runuser ubuntu --login --command \"juju model-defaults logging-config='<root>=INFO; unit=DEBUG'\"\n  - runuser ubuntu --login --command \"microk8s config > ~/.kube/config\"\n  - runuser ubuntu --login --command \"ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''\"\n  - runuser ubuntu --login --command \"cat ~/.ssh/id_ed25519.pub\"\n",
          "key": "user-data"
        },
        {
          "value": "ubuntu:ssh-ed25519 [redacted] ubuntu",
          "key": "ssh-keys"
        }
      ]
    },
    "shieldedVmConfig": {
      "enableSecureBoot": false,
      "enableVtpm": true,
      "enableIntegrityMonitoring": true
    },
    "shieldedInstanceConfig": {
      "enableSecureBoot": false,
      "enableVtpm": true,
      "enableIntegrityMonitoring": true
    },
    "serviceAccounts": [
      {
        "email": "370504277827-compute@developer.gserviceaccount.com",
        "scopes": [
          "https://www.googleapis.com/auth/devstorage.read_only",
          "https://www.googleapis.com/auth/logging.write",
          "https://www.googleapis.com/auth/monitoring.write",
          "https://www.googleapis.com/auth/servicecontrol",
          "https://www.googleapis.com/auth/service.management.readonly",
          "https://www.googleapis.com/auth/trace.append"
        ]
      }
    ],
    "displayDevice": {
      "enableDisplay": false
    }
  },
  "selfLink": "projects/dev-env-369519/global/instanceTemplates/dev-env"
}
```
</details>

LXD: `5.0.1`
juju: `2.9.37-ubuntu-amd64`
juju agent: `2.9.29`
charm rev: `96`
https://github.com/MiaAltieri/application-charm/commit/62529b113158f00940402a31042a70005394d4f3

# Log output
see https://github.com/canonical/mongodb-operator/issues/138#issuecomment-1347174286
<details>
<summary>juju status</summary>

```shell
Model     Controller  Cloud/Region         Version  SLA          Timestamp
tutorial  lxd         localhost/localhost  2.9.29   unsupported  19:23:22Z

App          Version  Status  Scale  Charm        Channel   Rev  Exposed  Message
application           active      1  application              0  no       
mongodb               error       1  mongodb      dpe/edge   96  no       hook failed: "update-status"

Unit            Workload  Agent  Machine  Public address  Ports      Message
application/0*  active    idle   1        10.77.125.173              
mongodb/0*      error     idle   0        10.77.125.248   27017/tcp  hook failed: "update-status"

Machine  State    Address        Inst id        Series  AZ  Message
0        started  10.77.125.248  juju-471887-0  focal       Running
1        started  10.77.125.173  juju-471887-1  focal       Running
```
</details>
